# Generated by Django 5.2.2 on 2026-04-19 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_allows_16plus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_allows_nsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_locks_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_restrict_dms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_minor_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='minor_age_range',
            field=models.CharField(blank=True, choices=[('under_13', 'Under 13'), ('13_15', '13-15'), ('16_17', '16-17')], max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='minor_age_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='minor_age_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='minor_birth_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='minor_birth_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='minor_birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='minor_birthdate_precision',
            field=models.CharField(blank=True, choices=[('age_range', 'Age range'), ('age_years', 'Age'), ('month_year', 'MM/YYYY'), ('full_date', 'DD/MM/YYYY')], max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='parental_controls_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('video', 'Video'), ('media', 'Media'), ('forum', 'Forum'), ('announcement', 'Announcement'), ('event', 'Event'), ('support', 'Support'), ('ticket', 'Ticket')], default='text', max_length=32),
        ),
        migrations.CreateModel(
            name='GuardianEmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='core_guardi_token_0e1148_idx'), models.Index(fields=['expires_at'], name='core_guardi_expires_d2f0e2_idx')],
            },
        ),
    ]
